### ISSUE TITLE
erros do tipo "[L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'"

### ISSUE THREAD

**Issue by leoalenc** [CompLin/nheengatu#645]
- [x] corrigir `Avila2021:0:0:436`
- [x] corrigir `Casasnovas2006:9:30:114`

```
Mon Nov 18 23:29:38 CET 2024
tools/check_files.pl UD_Nheengatu-CompLin
*** PASSED ***
./validate.sh --lang yrl --max-err 0 UD_Nheengatu-CompLin/yrl_complin-ud-test.conllu
[Line 12874 Sent Avila2021:0:0:436 Node 12]: 

- [ ] [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'

[Line 24978 Sent Casasnovas2006:9:30:114 Node 1]: [L3 Syntax rel-upos-advmod] 'advmod' should be 'ADV' but it is 'PRON'
Syntax errors: 2
*** FAILED *** with 2 errors
```

**Comment by leoalenc** [comment]
Relaciona-se com #353 .

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modify the handling of advmod relation for PRON in sentences Avila2021:0:0:436 and Casasnovas2006:9:30:114 to address syntax errors

You can review changes in this commit: https://github.com/lattaai13/CompLin-nheengatu-645/commit/b82e59b42b38314502637370c4515c3a407ef327.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
